# Generated by Django 4.0.5 on 2022-07-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_album_cover_alter_album_artist_delete_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='year',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
