# Generated by Django 4.0.6 on 2022-07-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0004_artist_remove_album_artist_album_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artists',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
